# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='header.proto',
  package='FileHeader',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cheader.proto\x12\nFileHeader\"\x95\x01\n\nHeaderInfo\x12\x15\n\rrecord_length\x18\x01 \x01(\r\x12\x17\n\x0frecord_per_page\x18\x02 \x01(\r\x12\x13\n\x0bpage_number\x18\x03 \x01(\r\x12\x15\n\rrecord_number\x18\x04 \x01(\r\x12\x19\n\x11next_vacancy_page\x18\x05 \x01(\r\x12\x10\n\x08\x66ilename\x18\x06 \x01(\tb\x06proto3')
)




_HEADERINFO = _descriptor.Descriptor(
  name='HeaderInfo',
  full_name='FileHeader.HeaderInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record_length', full_name='FileHeader.HeaderInfo.record_length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_per_page', full_name='FileHeader.HeaderInfo.record_per_page', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_number', full_name='FileHeader.HeaderInfo.page_number', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_number', full_name='FileHeader.HeaderInfo.record_number', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_vacancy_page', full_name='FileHeader.HeaderInfo.next_vacancy_page', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='FileHeader.HeaderInfo.filename', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['HeaderInfo'] = _HEADERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeaderInfo = _reflection.GeneratedProtocolMessageType('HeaderInfo', (_message.Message,), {
  'DESCRIPTOR' : _HEADERINFO,
  '__module__' : 'header_pb2'
  # @@protoc_insertion_point(class_scope:FileHeader.HeaderInfo)
  })
_sym_db.RegisterMessage(HeaderInfo)


# @@protoc_insertion_point(module_scope)
